### ISSUE TITLE
doesn't work on arch linux

### ISSUE THREAD

**Issue by 8u83r70** [imfunniee/youtube-discord-rpc#10]
error code: ENOENT
running discord canary on newest arch

**Comment by mutkach** [comment]
```
node:internal/errors:477
    ErrorCaptureStackTrace(err);
    ^

<ref *1> Error: spawnSync xwininfo ENOENT
    at Object.spawnSync (node:internal/child_process:1110:20)
    at spawnSync (node:child_process:837:24)
    at Object.execFileSync (node:child_process:880:15)
    at module.exports.sync (/home/nikita/Packages/youtube-discord-rpc/node_modules/active-win/lib/linux.js:72:36)
    at module.exports.sync (/home/nikita/Packages/youtube-discord-rpc/node_modules/active-win/index.js:25:33)
    at youtube (/home/nikita/Packages/youtube-discord-rpc/index.js:17:26)
    at Timeout._onTimeout (/home/nikita/Packages/youtube-discord-rpc/index.js:81:5)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync xwininfo',
  path: 'xwininfo',
  spawnargs: [ '-id', 481928 ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 0,
  stdout: null,
  stderr: null
}
```
